# Custom Language File for Launcher Customizer

[ejs.app]
title = "Moustach Launcher"

[ejs.landing]
mediaGitHubURL = "https://github.com/Yormaan/MoustachLauncher"
mediaXURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "https://discord.gg/yed7w9ZvmA"

[ejs.settings]
sourceGithubLink = "https://github.com/Yormaan/MoustachLauncher"
supportLink = "#"

[ejs.welcome]
welcomeHeader = "BIENVENIDOS A MOUSTACH LAUNCHER"
welcomeDescription = "En Moustach Studio nuestra misión es darte un punto de acceso único a todos nuestros servidores de Minecraft, presentes y futuros. Con el apoyo de nuestra comunidad, creamos mundos y experiencias —desde supervivencia y aventura hasta servidores con mods— cuidados al detalle para que explores, juegues con amigos y vivas historias inolvidables. Moustach Launcher se encarga de actualizaciones, dependencias y optimización por ti, para que solo elijas un servidor y juegues. El mundo es tuyo para descubrir. ¿Listo para empezar?"
welcomeDescCTA = "Solo unos clics te separan de la aventura."
